export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const ADD_USER = 'ADD_USER';
export const SET_USERS = 'SET_USERS';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const SET_USERACTIVE = 'SET_USERACTIVE';